max_width = 56
hard_tabs = false
tab_spaces = 2
fn_call_width = 32
attr_fn_like_width = 56
struct_lit_width = 18
struct_variant_width = 35
array_width = 32
chain_width = 32
single_line_if_else_max_width = 24
single_line_let_else_max_width = 24
short_array_element_width_threshold = 10
